

version: '3.8'
services:
  app:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && rails s -b '0.0.0.0'"
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    environment:
      PG_USER: postgres
      PG_PASS: 1234
      PG_HOST: db
      PG_PORT: 5432
      REDIS_URL: redis://redis:6379/1
    depends_on:
      - db
      - redis

  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: event_ticket_booking_development
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  test:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && rspec"
    volumes:
      - .:/app
    environment:
      RAILS_ENV: test
      PG_USER: postgres
      PG_PASS: 1234
      PG_HOST: db_test
      PG_PORT: 5432
      REDIS_URL: redis://redis_test:6379/1
    depends_on:
      - db_test
      - redis_test

  db_test:
    image: postgres
    environment:
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: event_ticket_booking_test
    volumes:
      - postgres_test_data:/var/lib/postgresql/data

  redis_test:
    image: redis
    volumes:
      - redis_test_data:/data

volumes:
  postgres_data:
  redis_data:
  postgres_test_data:
  redis_test_data: